name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Cache cargo
      id: cache-cargo
      uses: actions/cache@v3
      with:
        path: ~/.cargo
        key: ${{ hashFiles('Cargo.toml') }}

    - name: pgrx install
      if: ${{ steps.cache-cargo.outputs.cache-hit != 'true' }}
      run: cargo install --locked cargo-pgrx

    - name: Cache pgrx init
      id: cache-pgrx
      uses: actions/cache@v3
      with:
        path: ~/.pgrx
        key: ${{ hashFiles('Cargo.toml') }}

    - name: pgrx init
      if: ${{ steps.cache-pgrx.outputs.cache-hit != 'true' }}
      run: cargo pgrx init

    - name: Build
      run: cargo pgrx run

