name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Cache pgx
      id: cache-pgx
      uses: actions/cache@v3
      with:
        path: ~/.cargo
        key: ${{ hashFiles('Cargo.toml') }}

    - name: Prepare
      if: ${{ steps.cache-pgx.outputs.cache-hit != 'true' }}
      run: cargo install --locked cargo-pgx && cargo pgx init

    - name: Build
      run: cargo pgx run

